const quotes = [
  "The secret of getting ahead is getting started. — Mark Twain",
  "It always seems impossible until it's done. — Nelson Mandela",
  "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
  "You don't have to be great to start, but you have to start to be great. — Zig Ziglar",
  "Success is the sum of small efforts repeated day in and day out. — Robert Collier",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "The expert in anything was once a beginner. — Helen Hayes",
  "Push yourself, because no one else is going to do it for you.",
  "Small progress is still progress.",
  "Study hard, for the well is deep and our brains are shallow. — Richard Baxter",
  "The beautiful thing about learning is that no one can take it away from you. — B.B. King",
  "An investment in knowledge pays the best interest. — Benjamin Franklin",
  "The more that you read, the more things you will know. — Dr. Seuss",
  "Education is not the filling of a pail, but the lighting of a fire. — W.B. Yeats",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. — Gandhi",
  "The mind is not a vessel to be filled, but a fire to be kindled. — Plutarch",
  "It does not matter how slowly you go as long as you do not stop. — Confucius",
  "Don't let what you cannot do interfere with what you can do. — John Wooden",
  "You are braver than you believe, stronger than you seem, and smarter than you think. — A.A. Milne",
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Hardships often prepare ordinary people for an extraordinary destiny. — C.S. Lewis",
  "Strive for progress, not perfection.",
  "Your future is created by what you do today, not tomorrow.",
  "Dream big, start small, act now.",
  "Discipline is choosing between what you want now and what you want most.",
  "Success doesn't come from what you do occasionally, it comes from what you do consistently.",
  "Wake up with determination. Go to bed with satisfaction.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Do something today that your future self will thank you for.",
  "You didn't come this far to only come this far.",
  "Focus on being productive instead of busy. — Tim Ferriss",
];

export default quotes;
